### PR TITLE
Fixed Erlang 18.0 compile issues.

### PR DESCRIPTION
**Pull request by oubiwann**
This compiles on both Erlang 17 and 18.

### CODE REVIEW

**Comment by slevental** [comment]
@oubiwann Hello, I've just faced with a same issue when decided to move to erlang 18 having this library in dependencies. Thanks for fixing this! Any estimates on how long it takes ti be merged?

**Comment by fp** [comment]
@seansawyer is there any way this can get merged into master? I see this has conflicts and I have another version that I just did (before finding this one) which I could push if it make it easier to get it merged.

**Comment by oubiwann** [comment]
I've updated the PR to remove the conflict, so it should be good for merge now.

All tests are passing on Travis CI for R15B03, R16B03-1, 17.5, 18.0, and 18.3:
 * https://travis-ci.org/lfe-support/erlang_iso8601

**Comment by oubiwann** [comment]
@slevental  @fp  Based on the fairly extensive Github [Network graph](https://github.com/seansawyer/erlang_iso8601/network) for this project (all the forks, branches, etc.) I'm guessing that the possibility of a PR merge is pretty low ... but @seansawyer might surprise us!

**Comment by seansawyer** [comment]
First of all, let me apologize for completely neglecting this repo! I don't have the pleasure of using Erlang these days.

Second, with the `src_dirs` options in __rebar.config__ I get a `badmatch`. Without them, things work fine. Do you need these options for a particular reason? If you can do without them I'm happy to merge and remove them.

Lastly, I'd like to find a new maintainer. Any chance you'd take that on or know someone who might? :wink:

**Comment by oubiwann** [comment]
@seansawyer Hey! No worries at all :-)

I've updated the ``rebar.config`` file and the tests are re-running in Travis right now.

I'd be happy to maintain the repo. Perhaps we can talk @tsloughter into forking it to Erlware and adding me to the org? Then we can update the README and project URL to point to the new home ...

@tsloughter What do you think?

**Comment by oubiwann** [comment]
Well, I guess we wouldn't want to fork -- that would lose issue history, etc.

**Comment by oubiwann** [comment]
@seansawyer I've just created an org that doesn't put Erlware into an awkward position (their erlware_commons repo has an ec_date library).

If you are okay with it, you can transfer this repo to the following org:
 * https://github.com/erlsci

**Comment by seansawyer** [comment]
@oubiwann Sure, I'm fine with that. You cool with me forking after the transfer and updating the README on my fork to point to the canonical repo? Just to keep people's builds from breaking if they're pointing at the old repo.

**Comment by oubiwann** [comment]
@seansawyer Sure thing! Github does do auto-forwarding (even at the git pull/push level), but I think you're right -- it would be nice documentation for users :-)

I'll also tag the latest (if you haven't already) so that there's a version that represents the code at the point of transition ...

**Comment by seansawyer** [comment]
@oubiwann Oh cool, didn't know that about auto-forwarding. Will start the transfer now.

**Comment by seansawyer** [comment]
Oh actually, I need admin rights to the org, at least temporarily.

**Comment by oubiwann** [comment]
Done!

**Comment by fp** [comment]
@oubiwann @seansawyer where did we end up on transferring maintainership? I'm also happy to help in any way...

**Comment by seansawyer** [comment]
@fp @oubiwann Tried to transfer to the **erlsci** org but got a message complaining I didn't have admin rights. This was after @oubiwann added me to the org. Then got distracted and didn't post back here.

**Comment by seansawyer** [comment]
@fp @oubiwann Nevermind, I'm an idiot. The invitiation was still pending. Should be transferred momentarily.

**Comment by fp** [comment]
@seansawyer wonderful, I see this now transferred!

@oubiwann can we get the erlang 18 changes merged?

**Comment by oubiwann** [comment]
Yes! Let's do it now!

@seansawyer Thanks so much for this -- it will really help :-)

**Pull request merged**
